README.md
This PR adds the release steps for Watchful Python Package, so that Watchful folks or collaborating users can publish releases to PyPI.
=> Watchful Python Package Release Steps

src/watchful/client.py
Adds an exception type that was missing from `exit_backend()` (found by API fuzz testing by tests/0040*).
=> fix exit_backend() race condition

README.md
This PR adds basic usage and enrichment notes as well as links to the more thorough usage examples in the `examples` directory. 
This is mean to help users discover documentation rather than supplant the existing notebooks.
=> Add basic usage and enrichment notes to readme

pyproject.toml, src/watchful/__init__.py, src/watchful/attributes.py, src/watchful/client.py, tests/test_attributes.py
This patch brings the total test coverage up to 30% as a result of adding some testing for some of the functions in `attributes.py` - its own coverage is now 37%.
Some of these functions will be difficult to test due to the quasi-concurrent nature of attributes. This not an interface that we should lean into at all, and is adding complexity (and, surely, bugs) where we don't need it.
=> test: add initial attributes tests

.circleci/config.yml
Updates all the steps to use a filter because `publish` and `send-slack-notification` have filters. See [this page](https://circleci.com/docs/workflows/#executing-workflows-for-a-git-tag) for more info
=> Add filters to all steps

release.sh
Releases should not be triggered automatically, but the process should be as automated as possible to prevent human errors breaking dependent automation. This patch introduces a script that can serve as the trigger, and handle the initial automation (and trigger downstream automation). See the release script header for more information.
=> chore: add release script

src/watchful/enrich.py
This patch fixes a bug where enrichment via https could not occur. The bug occurs because we step use the default scheme when running `watchful.enrich.main`, and which will then always be `http`, and can never be overridden.
=> fix: no step on scheme

.circleci/config.yml, .gitignore, pyproject.toml
This patch adds the necessary functionality to cache dependencies in CircleCI. This isn't _strictly_ needed, but it would certainly speed up the CI process, particualarly in cases where we're working to push a change out quickly.
=> chore: cache dependencies in CircleCI

src/watchful/client2.py, tests/client/test_client.py
This patch adds `set_config` and `get_config` functionality to the new `Client`.
Additionally, it implements `set_hub_url`, though it does it via a different interface than the original client. The original client
used `/set_hub_url`, which does some transformations and then does the equivalent of `set_config("remote", ...)` on the backend. The new `Client` interface opts to use `POST /config` instead of the old endpoint. The old endpoint, `POST  set_hub_url` should be deprecated and removed.
=> feat: add set_config/get_config to new Client

.circleci/config.yml
When there was a `v` prefix on releases, we'd want to trim that off for notifying slack (this should have been a hint that it's not important). This patch fixes an issue where relevant information is now being trimmed off.
=> fix: don't trim the tag on release

src/watchful/client2.py, tests/client/test_client.py
This patch implement the functionality that interacts with a hub instance. The remote api is a little shaky here, as sometimes it will return json and sometimes it will return a plain string (which the server side considers a valid json value, and python does not).
=> feat: add remote api functionality to new Client

src/watchful/client2.py, src/watchful/types.py, tests/client/test_client.py
This patch implements the `create_class` and `delete_class` functionality for the new `Client` interface.
=> feat: implement create_class/delete_class

.circleci/config.yml
The `check` step of CI takes the longest, and it does so because `ruff` and `mypy` both have to start from scratch in their analysis. This patch keeps the caches from both commands so that they can be reused in the next run. This sholud make the the `check` step much quicker.
=> chore: save mypy and ruff caches

src/watchful/client2.py, tests/client/test_client.py
This patch implements the `create_hinter`,
`create_external_hinter`, and `delete_hinter` methods in the new `Client` interface.
=> feat: add hinter creation and deletion

src/watchful/client.py, src/watchful/client2.py, src/watchful/types.py, tests/client/test_client.py
This PR adds support for the `enrichable` column flag by mostly copying/extending the support that was in place for the `inferenceable` flag.
Closes [sc-10980](https://app.shortcut.com/watchful/story/10980/update-python-lib-to-support-enrichable)
=> Add support for enrichable column flags

pyproject.toml
`watchful` has a dependency on `requests` that we never included in our python dependency. This patch remedies that.
Additionally, the next version of watchful-py will require a version of python that is still being maintained.
=> chore: add requests dependency

src/watchful/client.py
WF-164
#359 introduced an issue where we were encoding the `mode` and `content-type` parameters twice. This PR fixes that issue
=> WF-164 correct encoding procedure

src/watchful/__init__.py, src/watchful/attributes.py, src/watchful/client.py, src/watchful/client2.py, src/watchful/enrich.py, src/watchful/enricher.py
[WF-141](https://watchful.atlassian.net/browse/WF-141)
This PR adds register method to the Client class, so that it can be used to register user in the integration tests. It takes in 
1. verb
2. username
3. email
4. password
5. role
and sends back a Json<str, str>
[WF-141]: https://watchful.atlassian.net/browse/WF-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add proxy method to register user using remote api from app

examples/enrichment_intro.ipynb, pyproject.toml, src/watchful/__init__.py, src/watchful/attributes.py, src/watchful/client.py, src/watchful/enrich.py, tests/client/test_api.py, tests/test_attributes.py
As part of the work in WF-391 to clean up our internal APIs, this PR removes all usage of the `datasets` property on project summaries in the Python API.
Where (I thought it) possible, I refactored affected codepaths to continue functioning when manually presented with a `dataset_id` (though I'm unsure if these paths are even needed?).
=> WF-391: Remove/refactor usage of the  property on project summaries

src/watchful/client.py, tests/client/test_api.py
Need to update here so integrations tests continue to work now that we've changed the `POST /projects` endpoint
=> Update open_project and create_project to match wf-540
